In [2]:
import numpy as np
import pandas as pd

In [3]:
df= pd.read_csv('MegaMart_sales.csv')

In [4]:
df_new= pd.read_csv('MegaMart_newsales.csv')

#### Combining two data frames
Question 1: Some of the orders are stored in another csv file named `megamart_new sales`. Read the csv file, store it in a data frame and add it to the `megamart_sales` data frame. Find the total sales value of the category 'Office Supplies'  after combining the dataframes

    a)7970
    b)6964
    c)7494
    d)6076

In [5]:
#your code here
frames = [df,df_new]
result = pd.concat(frames)
answer = result[result['Category'] == 'Office Supplies']
answer.sum(axis=0)

Order ID        AZ-2011-1029887AZ-2011-1362199AZ-2011-1116129A...
Product Name    Novimex Color Coded Labels, 5000 Label SetSanf...
Discount                                                      4.7
Sales                                                        7970
Profit                                                       1338
Quantity                                                      169
Category        Office SuppliesOffice SuppliesOffice SuppliesO...
Sub-Category    LabelsArtBindersSuppliesLabelsArtStorageBinder...
dtype: object

#### Dropping duplicates
Question 2: There are some duplicate rows in the data frame. Drop these rows and calculate the total sales value of the category Office Supplies.

    a)7156
    b)6496
    c)6964
    d)6023

In [6]:
#your code here
frames = [df,df_new]
result = pd.concat(frames)
result.drop_duplicates(inplace=True)
answer = result[result['Category'] == 'Office Supplies']
answer.sum(axis=0)

Order ID        AZ-2011-1029887AZ-2011-1362199AZ-2011-1116129A...
Product Name    Novimex Color Coded Labels, 5000 Label SetSanf...
Discount                                                      3.6
Sales                                                        6964
Profit                                                       1045
Quantity                                                      149
Category        Office SuppliesOffice SuppliesOffice SuppliesO...
Sub-Category    LabelsArtBindersSuppliesLabelsArtStorageBinder...
dtype: object

#### Best category-sub category 
Question 3: Find the most profitable category and sub category combination based on the net profit.


    a)Furniture-Bookcases
    b)Office supplies-Appliances
    c)Office supplies-Storage
    d)Technology-Phones

In [15]:
#your code here
frames = [df,df_new]
result = pd.concat(frames)
result.groupby(["Category","Sub-Category"]).Profit.sum()

Category         Sub-Category
Furniture        Bookcases        308
                 Chairs           -49
                 Furnishings       74
Office Supplies  Appliances       229
                 Art              283
                 Binders          158
                 Envelopes         35
                 Fasteners         10
                 Labels            30
                 Paper             15
                 Storage          475
                 Supplies         103
Technology       Accessories      324
                 Copiers            0
                 Machines         336
                 Phones          1618
Name: Profit, dtype: int64

#### Invalid order IDs
Question 4: How many invalid order IDs are there in the data frame. An order id is of the form AZ-2011-Y where Y represents a whole number. A Order ID is said to be valid only if Y consists of 7 digits. Find the number of valid order order IDs in the data frame.
    
    a)6
    b)7
    c)8
    d)9

In [57]:
#your code here
#your code here
frames = [df,df_new]
result = pd.concat(frames)
result[result['Order ID'].astype(str).str[8:].str.len() != 7].count()

Order ID        7
Product Name    7
Discount        7
Sales           7
Profit          7
Quantity        7
Category        7
Sub-Category    7
dtype: int64

#### Occurence of furniture in top 25 sales
Question 5: Find the top 25 orders based on sales value and find the number of orders which belong to furniture category.

    a)2
    b)3
    c)4
    d)5

In [72]:
#your code here
frames = [df,df_new]
result = pd.concat(frames)
df2=result.sort_values(by='Sales', ascending=False)
df2=df2.iloc[:25,]

df2['Category'].value_counts()

Technology         11
Office Supplies    10
Furniture           4
Name: Category, dtype: int64

#### And operation
Question 6: Among the orders with sales>250 and profit>50, find the product name of the fourth highest order based on sales value.

    a)Motorola Headset, with Caller ID
    b)Panasonic Printer, Durable	
    c)Hoover Microwave, Red	
    d)Fellowes Lockers, Industrial

In [83]:
#your code here
frames = [df,df_new]
result = pd.concat(frames)
sales = result[result['Sales'] > 250]
profits = sales[sales['Profit'] > 50]
profits.sort_values(by='Sales',ascending=False)

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
30,AZ-2011-1410648,"Nokia Smart Phone, Full Size",0.0,1908,820,3,Technology,Phones
58,AZ-2011-176674,"Hoover Microwave, Red",0.1,1667,185,6,Office Supplies,Appliances
8,AZ-2011-1174243,"Nokia Audio Dock, with Caller ID",0.0,1334,200,8,Technology,Phones
20,AZ-2011-1322840,"Motorola Headset, with Caller ID",0.0,957,316,12,Technology,Phones
28,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
3,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
18,AZ-2011-1406494,"Fellowes Lockers, Industrial",0.1,748,283,4,Office Supplies,Storage
29,AZ-2011-1406494,"Fellowes Lockers, Industrial",0.1,748,283,4,Office Supplies,Storage
39,AZ-2011-1536006,"Logitech Keyboard, Programmable",0.0,666,66,9,Technology,Accessories
33,AZ-2011-1445262,"Apple Smart Phone, Cordless",0.0,636,140,1,Technology,Phones
31,AZ-2011-144325,"Bush Stackable Bookrack, Pine",0.0,630,132,5,Furniture,Bookcases
14,AZ-2011-1260928,"Eldon File Cart, Single Width",0.1,576,51,5,Office Supplies,Storage
12,AZ-2011-1253407,"Safco Stackable Bookrack, Pine",0.1,541,156,4,Furniture,Bookcases
48,AZ-2011-1672552,"Binney & Smith Sketch Pad, Blue",0.0,510,132,11,Office Supplies,Art
52,AZ-2011-1722024,"Cisco Audio Dock, VoIP",0.0,364,142,2,Technology,Phones
0,AZ-2011-1902971,"Wilson Jones Binding Machine, Clear",0.0,339,102,7,Office Supplies,Binders
17,AZ-2011-130330,"Office Star Chairmat, Adjustable",0.1,307,99,5,Furniture,Chairs
13,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories
2,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories

#### Column manipulation
Question 7: Remove the orders with negative profit by dropping the corresponding rows with negative `Profit`. Find the product that makes the lowest profit per Quantity in the Technology category.

    a) Nokia Audio Dock, with Caller ID
    b) Logitech Keyboard, Programmable
    c) Motorola Headset, with Caller ID
    d) Belkin Flash Drive, Bluetooth

In [88]:
#your code here
frames = [df,df_new]
result = pd.concat(frames)


profitable  = result[result.Profit > 0]
                                                  
profitable['Profit per Quantity'] = profitable.Profit / profitable.Quantity
profitable[profitable.Category == 'Technology'].sort_values(by='Profit per Quantity')

<ipython-input-88-26e245d3805b>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  profitable['Profit per Quantity'] = profitable.Profit / profitable.Quantity

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category,Profit per Quantity
39,AZ-2011-1536006,"Logitech Keyboard, Programmable",0.0,666,66,9,Technology,Accessories,7.333333
2,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories,15.571429
13,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories,15.571429
4,AZ-2011-1967754,"Logitech Numeric Keypad, USB",0.0,93,40,2,Technology,Accessories,20.000000
8,AZ-2011-1174243,"Nokia Audio Dock, with Caller ID",0.0,1334,200,8,Technology,Phones,25.000000
20,AZ-2011-1322840,"Motorola Headset, with Caller ID",0.0,957,316,12,Technology,Phones,26.333333
3,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines,56.000000
28,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines,56.000000
52,AZ-2011-1722024,"Cisco Audio Dock, VoIP",0.0,364,142,2,Technology,Phones,71.000000
33,AZ-2011-1445262,"Apple Smart Phone, Cordless",0.0,636,140,1,Technology,Phones,140.000000
30,AZ-2011-1410648,"Nokia Smart Phone, Full Size",0.0,1908,820,3,Technology,Phones,273.333333